### ISSUE TITLE
Votefinder deadlines showing as *DT instead of *ST

### ISSUE THREAD

**Issue by podima17** [velinath/votefinder-web#74]
May be a PEBKAC error - only happening for Ecco's game and not others. Cannot reproduce.

Time zone seems to default to current user's time zone - keyed off of system time?

**Comment by velinath** [comment]
The display should be based off of user's time zone, yes, by default. I remember this being something I had to look into because the time did interesting things during a server migration and will provide more details when I have a chance to look over it.

**Comment by velinath** [comment]
ref #56 but I don't think it's the same

i see that the other games are running in Standard and not Daylight currently which I find particularly interesting

**Comment by velinath** [comment]
working as intended; March 11 this year is the DST cutover
